/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import controllerJuegos.InfoVideoJuegos;
import controllerJuegos.Juego;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.GameDates;
import view.Inicio;
/**
 *
 * @author claudia
 */
public class InicioSesion extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();
    private final UsuarioController USUARIO = new UsuarioController();
    private final InfoVideoJuegos JUEGOS = new InfoVideoJuegos();
    String game = JUEGOS.juegos();

    public InicioSesion() {
        this.setContentPane(fondo);
        setMinimumSize(new Dimension(1000, 600)); // Ajusta el tamaño según tu imagen de fondo
        
        initComponents();
        jPInicioContraseña.setEchoChar('\u2022');
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTinicioUsuario = new javax.swing.JTextField();
        jPInicioContraseña = new javax.swing.JPasswordField();
        jBInicio = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();
        jLCrear = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLEntrada = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLContraseña = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(java.awt.Color.darkGray);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 2));
        jPanel2.setForeground(java.awt.Color.darkGray);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 380));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Inicio de sesión");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTinicioUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jTinicioUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jTinicioUsuario.setForeground(java.awt.Color.white);
        jTinicioUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 56, 169), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(108, 56, 169), 1, true)));
        jTinicioUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTinicioUsuario.setDisabledTextColor(new java.awt.Color(70, 73, 75));
        jTinicioUsuario.setSelectionColor(new java.awt.Color(153, 0, 255));
        jTinicioUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTinicioUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTinicioUsuarioFocusLost(evt);
            }
        });
        jTinicioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTinicioUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jTinicioUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 40));

        jPInicioContraseña.setBackground(new java.awt.Color(51, 51, 51));
        jPInicioContraseña.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jPInicioContraseña.setForeground(java.awt.Color.white);
        jPInicioContraseña.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 56, 169), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(108, 56, 169), 1, true))));
        jPInicioContraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        jPInicioContraseña.setDisabledTextColor(new java.awt.Color(70, 73, 75));
        jPInicioContraseña.setSelectionColor(new java.awt.Color(153, 0, 255));
        jPInicioContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPInicioContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPInicioContraseñaFocusLost(evt);
            }
        });
        jPanel2.add(jPInicioContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 520, 40));

        jBInicio.setBackground(new java.awt.Color(103, 22, 199));
        jBInicio.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jBInicio.setForeground(java.awt.Color.white);
        jBInicio.setText("Iniciar sesión");
        jBInicio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4)));
        jBInicio.setFocusable(false);
        jBInicio.setVerifyInputWhenFocusTarget(false);
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 504, 40));

        jBRegresar.setBackground(java.awt.Color.darkGray);
        jBRegresar.setForeground(java.awt.Color.darkGray);
        jBRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Repositorio/BotonRegresar.png"))); // NOI18N
        jBRegresar.setBorder(null);
        jBRegresar.setBorderPainted(false);
        jBRegresar.setContentAreaFilled(false);
        jBRegresar.setDefaultCapable(false);
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 40));

        jLCrear.setBackground(java.awt.Color.white);
        jLCrear.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLCrear.setForeground(java.awt.Color.white);
        jLCrear.setText("¿No tienes una cuenta?");
        jLCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCrearMouseClicked(evt);
            }
        });
        jPanel2.add(jLCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPanel3.setBackground(java.awt.Color.darkGray);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLEntrada.setBackground(new java.awt.Color(255, 255, 255));
        jLEntrada.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jLEntrada.setToolTipText("");
        jPanel3.add(jLEntrada);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 390, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Usuario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jPanel4.setBackground(java.awt.Color.darkGray);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jLContraseña.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLContraseña.setForeground(java.awt.Color.white);
        jPanel4.add(jLContraseña);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 430, 30));

        jPanel5.setBackground(java.awt.Color.darkGray);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLError.setBackground(new java.awt.Color(255, 255, 255));
        jLError.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLError.setForeground(java.awt.Color.white);
        jPanel5.add(jLError);

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 330, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Contraseña");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        getContentPane().add(jPanel2, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTinicioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTinicioUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTinicioUsuarioActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
            String entrada = jTinicioUsuario.getText().trim();
    String contraseña = jPInicioContraseña.getText().trim();
    boolean error = false;

    //validar primero el admin
    if (entrada.equalsIgnoreCase("admin") && contraseña.equals("admin12345")) { 
        PerfilAdmin abrir = new PerfilAdmin();
        abrir.setVisible(true);
        this.setVisible(false);
        return; // Salir del metodo liego de de abrir el perfil de admin
    }

    // **VALIDAR USUARIO NORMAL**
    boolean usuarioExiste = USUARIO.existeUsuario(entrada);
    boolean contraseñaCorrecta = USUARIO.contraseñaCorrecta(contraseña);

    // Limpiar mensajes de error 
    jLError.setText("");
    jLEntrada.setText("");
    jLContraseña.setText("");

    if (entrada.isEmpty() || contraseña.isEmpty()) {
        jLError.setForeground(Color.RED);
        jLError.setText("Cree una cuenta");
        error = true;
    }

    if (!usuarioExiste) {
        jLEntrada.setForeground(new Color(255, 141, 141));
        jLEntrada.setText("Ingrese un usuario válido*");
        error = true;
    } else if (!contraseñaCorrecta) {
        jLContraseña.setForeground(Color.RED);
        jLContraseña.setText("Contraseña incorrecta*");
        error = true;
    }

    if (!error) {
        USUARIO.validarInicioSesion(entrada, contraseña);
        BibliotecaGeneral abrir = new BibliotecaGeneral();
        abrir.setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        Inicio abrir = new Inicio();
        
        if(this.getExtendedState() == Inicio.MAXIMIZED_BOTH){
            abrir.setExtendedState(Inicio.MAXIMIZED_BOTH);
        }
        
        abrir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jTinicioUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTinicioUsuarioFocusGained
        if (jTinicioUsuario.getText().equals("Ingrese usuario o correo registrado")) {
        jTinicioUsuario.setText("");
        jTinicioUsuario.setForeground(Color.WHITE); // cambia al color normal
}
    }//GEN-LAST:event_jTinicioUsuarioFocusGained

    private void jTinicioUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTinicioUsuarioFocusLost
        if (jTinicioUsuario.getText().isEmpty()) {
        jTinicioUsuario.setText("Ingrese usuario o correo registrado");
        jTinicioUsuario.setForeground(Color.GRAY); // vuelve a gris si está vacío
        }
    }//GEN-LAST:event_jTinicioUsuarioFocusLost

    private void jPInicioContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPInicioContraseñaFocusGained
        if (String.valueOf(jPInicioContraseña.getPassword()).equals("Ingrese su contraseña")) {
        jPInicioContraseña.setText("");
        jPInicioContraseña.setForeground(Color.WHITE);
        jPInicioContraseña.setEchoChar('\u2022');
        } // Activa el ocultamiento
    }//GEN-LAST:event_jPInicioContraseñaFocusGained

    private void jPInicioContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPInicioContraseñaFocusLost
        if (String.valueOf(jPInicioContraseña.getPassword()).isEmpty()) {
        jPInicioContraseña.setText("Ingrese su contraseña");
        jPInicioContraseña.setForeground(Color.GRAY);
        jPInicioContraseña.setEchoChar((char) 0); 
        }// Desactiva el ocultamiento
    }//GEN-LAST:event_jPInicioContraseñaFocusLost

    private void jLCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCrearMouseClicked
        Registro abrir = new Registro();
        
        if(this.getExtendedState() == Inicio.MAXIMIZED_BOTH){
            abrir.setExtendedState(Inicio.MAXIMIZED_BOTH);
        }
        
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLCrear;
    private javax.swing.JLabel jLEntrada;
    private javax.swing.JLabel jLError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPInicioContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTinicioUsuario;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Repositorio/FondoInicioSesion.png")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
}

